### ISSUE TITLE
How fix?

### ISSUE THREAD

**Issue by RochardRA** [brandonmanke/steam-2fa#1]
https://user-images.githubusercontent.com/24755448/29004382-4fe00556-7acf-11e7-9086-38246b190871.png

**Comment by brandonmanke** [comment]
I don't know the entire contents of your `o.js` file, or what specifically you changed but the problem is in your details object - which is undefined. You need to either create a details object with your account name and password as properties or replace details with a similar object.

![details object](https://user-images.githubusercontent.com/8422261/29006189-9e6b2832-7ab0-11e7-83aa-efe4461dc5aa.png)

Also this file is only for enabling 2 factor authentication on steam accounts, and generating a file with the accounts sensitive info.

**Comment by RochardRA** [comment]
[2fa.txt](https://github.com/brandonmanke/steam-2fa/files/1203363/2fa.txt)

**Comment by brandonmanke** [comment]
Can you just upload the code to pastebin or something?

**Comment by RochardRA** [comment]
https://pastebin.com/AW67Tuc6

**Comment by brandonmanke** [comment]
Ok so you added `accountLogin();` on line 31, there are two reasons why this won't work one is because you're passing no parameters to this function. But also I also call this same function with details passed as the parameter on line 124. So to fix it just remove the accountLogin call on line 31.

**Comment by RochardRA** [comment]
But then the program freezes...

**Comment by brandonmanke** [comment]
What do you mean freezes?

**Comment by RochardRA** [comment]
![default](https://user-images.githubusercontent.com/24755448/29006580-6b11eae8-7afb-11e7-8c8a-0f2e35618df2.PNG)

The program has stopped

**Comment by brandonmanke** [comment]
That isn't running the program you just opened Node.exe, you need to navigate to the directory the file is in and run `node filename`.

**Comment by RochardRA** [comment]
![default](https://user-images.githubusercontent.com/24755448/29006665-f2f5a980-7afc-11e7-8a0d-a45df5e48705.PNG)
┌( ಠ_ಠ)┘

**Comment by brandonmanke** [comment]
Alright well I'm sorry I can't help with this any further I haven't really worked on this repo for a while, so it probably has some stupid bugs. My recommendation is to use this:
https://github.com/Jessecar96/SteamDesktopAuthenticator

It is probably 100000x better than this and easier to set up. Sorry about that 😞

**Comment by RochardRA** [comment]
Ye i saw that, but it in c# (ノಠ益ಠ)ノ彡┻━┻

**Comment by brandonmanke** [comment]
What are you using this for? Because it would accomplish the same thing?

**Comment by RochardRA** [comment]
I want to make Automatic enable 2fa on accounts with onlinesim service

**Comment by brandonmanke** [comment]
Maybe try (this)[https://github.com/DoctorMcKay/node-steamcommunity/blob/master/examples/enable_twofactor.js]

**Comment by RochardRA** [comment]
Yes i saw it, but at first need add phone...

**Comment by brandonmanke** [comment]
And just to be sure, no error message shows up? Just completely blank.

**Comment by RochardRA** [comment]
+

**Comment by brandonmanke** [comment]
If you have any other node scripts and you run them do they work?

**Comment by RochardRA** [comment]
Ye they work

**Comment by brandonmanke** [comment]
Ok well I am sorry, this repo is probably broken then. I wasn't able to reproduce the bug on my end.

**Comment by RochardRA** [comment]
:)
